namespace: postgres-operator

commonLabels:
  app.kubernetes.io/name: pgo
  app.kubernetes.io/version: 5.0.4
  postgres-operator.crunchydata.com/control-plane: postgres-operator

bases:
- crd
- rbac/cluster
- manager

images:
- name: postgres-operator
  newName: registry.developers.crunchydata.com/crunchydata/postgres-operator
  newTag: ubi8-5.0.4-0
